spring:
  datasource:
    url: ${MARIADB_URL}  # URL을 MariaDB용으로 변경
    driver-class-name: org.mariadb.jdbc.Driver       # 드라이버 클래스를 MariaDB용으로 변경
    username: ${MARIADB_USERNAME}                           # MariaDB 사용자명
    password: ${MARIADB_PASSWORD}                           # MariaDB 비밀번호

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect  # 데이터베이스 플랫폼을 MariaDB로 변경
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show_sql: true
#    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always