spring:
  profiles:
    active: local     #loal prod
    include: oauth
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: ${MAIL_USERNAME} # 3
    password: ${MAIL_PASSWORD} # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
  karaoke:
    search-url: https://api.manana.kr/v2/karaoke/search.json
    release-url: https://api.manana.kr/v2/karaoke/release.json

jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 1800