INSERT INTO AUTHORITY(AUTHORITY_NAME) VALUES ('ROLE_ADMIN');
INSERT INTO AUTHORITY(AUTHORITY_NAME) VALUES ('ROLE_USER');
INSERT INTO USERS(ACTIVATED, PASSWORD, USER_ID, USER_NAME, USER_SEQ) VALUES(TRUE, '$2a$10$OJtaRJO5NDWAgAzZeGyfpuWGWxJ1BfnTwT0nmO9UNZ1O.IHPXfSfy', 'aamoos@naver.com', '김재성', '2');
INSERT INTO USER_AUTHORITY(USER_SEQ, AUTHORITY_NAME) VALUES('2', 'ROLE_USER');